# Generated by Django 6.0.5 on 2026-05-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangPersediaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=30, unique=True)),
                ('nama_barang', models.CharField(max_length=150)),
                ('stok', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('satuan', models.CharField(default='kg', max_length=30)),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Barang Persediaan',
                'verbose_name_plural': 'Daftar Barang Persediaan',
                'db_table': 'barang_persediaan',
            },
        ),
        migrations.CreateModel(
            name='MutasiPersediaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tipe_mutasi', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar'), ('penyesuaian', 'Penyesuaian')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_setelah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persediaan.barangpersediaan')),
            ],
            options={
                'verbose_name': 'Mutasi Persediaan',
                'verbose_name_plural': 'Riwayat Mutasi Persediaan',
                'db_table': 'mutasi_persediaan',
                'ordering': ['-tanggal', '-id'],
            },
        ),
    ]
