# Generated by Django 5.2.14 on 2026-05-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0002_jurnalheader_nomor_bukti_opsional'),
        ('persediaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutasipersediaan',
            name='akun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='akuntansi.akun'),
        ),
        migrations.AddField(
            model_name='mutasipersediaan',
            name='harga_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='mutasipersediaan',
            name='nomor_dokumen',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
