# Generated by Django 5.2.14 on 2026-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relasi_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_kartu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='saldo_saat_ini',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplier',
            name='no_kartu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='saldo_saat_ini',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
