# Generated by Django 6.0.5 on 2026-05-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(max_length=10, unique=True)),
                ('nama_akun', models.CharField(max_length=150)),
                ('kategori_akun', models.CharField(choices=[('aset', 'Aset'), ('kewajiban', 'Kewajiban'), ('ekuitas', 'Ekuitas'), ('pendapatan', 'Pendapatan'), ('hpp', 'HPP'), ('beban_operasional', 'Beban Operasional'), ('pendapatan_lain', 'Pendapatan Lain-lain'), ('beban_lain', 'Beban Lain-lain')], max_length=30)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'akun',
                'ordering': ['kode_akun'],
            },
        ),
        migrations.CreateModel(
            name='JurnalHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nomor_bukti', models.CharField(max_length=50, unique=True)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('sumber_transaksi', models.CharField(default='manual', max_length=50)),
            ],
            options={
                'db_table': 'jurnal_header',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JurnalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='akuntansi.akun')),
                ('jurnal_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_jurnal', to='akuntansi.jurnalheader')),
            ],
            options={
                'db_table': 'jurnal_detail',
            },
        ),
    ]
