# Generated by Django 6.0.5 on 2026-05-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persediaan', '0001_initial'),
        ('relasi_bisnis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PembayaranUtang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nomor_bukti', models.CharField(max_length=50, unique=True)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relasi_bisnis.supplier')),
            ],
            options={
                'db_table': 'pembayaran_utang',
            },
        ),
        migrations.CreateModel(
            name='PembelianBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nomor_invoice', models.CharField(max_length=50, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status_pembayaran', models.CharField(choices=[('lunas', 'Lunas'), ('utang', 'Utang')], max_length=20)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relasi_bisnis.supplier')),
            ],
            options={
                'db_table': 'pembelian_barang',
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PembelianDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persediaan.barangpersediaan')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pembelian', to='pembelian.pembelianbarang')),
            ],
            options={
                'db_table': 'pembelian_detail',
            },
        ),
    ]
