# Generated by Django 5.2.14 on 2026-05-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0002_jurnalheader_nomor_bukti_opsional'),
        ('pembelian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaranutang',
            name='akun_kas_bayar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran_utang_kas', to='akuntansi.akun'),
        ),
        migrations.AddField(
            model_name='pembayaranutang',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pembayaranutang',
            name='no_cek',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pembelianbarang',
            name='diskon_persen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pembelianbarang',
            name='nomor_faktur_pemasok',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pembelianbarang',
            name='pajak_persen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pembelianbarang',
            name='termin_pembayaran',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
