# Generated by Django 6.0.5 on 2026-05-28 15:54

from django.db import migrations, models


def lunas_ke_tunai(apps, schema_editor):
    PembelianBarang = apps.get_model("pembelian", "PembelianBarang")
    PembelianBarang.objects.filter(status_pembayaran="lunas").update(status_pembayaran="tunai")


def tunai_ke_lunas(apps, schema_editor):
    PembelianBarang = apps.get_model("pembelian", "PembelianBarang")
    PembelianBarang.objects.filter(status_pembayaran="tunai").update(status_pembayaran="lunas")


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0002_pembayaranutang_akun_kas_bayar_and_more'),
    ]

    operations = [
        migrations.RunPython(lunas_ke_tunai, tunai_ke_lunas),
        migrations.AlterField(
            model_name='pembelianbarang',
            name='status_pembayaran',
            field=models.CharField(choices=[('tunai', 'Tunai'), ('utang', 'Utang')], max_length=20),
        ),
    ]
