# Generated by Django 6.0.5 on 2026-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduksiPanen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('komoditas', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=30)),
                ('jumlah_hasil_panen', models.DecimalField(decimal_places=2, max_digits=18)),
                ('satuan', models.CharField(default='kg', max_length=30)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'produksi_panen',
                'ordering': ['-tanggal', '-id'],
            },
        ),
    ]
