# Generated by Django 5.2.14 on 2026-05-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0002_jurnalheader_nomor_bukti_opsional'),
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerimaanpiutang',
            name='akun_kas_setoran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penerimaan_piutang_setoran', to='akuntansi.akun'),
        ),
        migrations.AddField(
            model_name='penerimaanpiutang',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='penerimaanpiutang',
            name='faktur_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='penjualanbarang',
            name='diskon_persen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='penjualanbarang',
            name='pajak_persen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='penjualanbarang',
            name='termin_pembayaran',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
